name: CI

on:
  pull_request:
    branches:
      - main # Runs on PRs targeting `main` branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Clear webpack cache
        run: rm -rf .next/cache

      - name: Install dependencies
        run: npm install

      - name: Install i18nexus CLI
        run: npm install -g i18nexus-cli

      - name: Run ESLint
        run: npm run lint

      # - name: Run Jest Unit Tests
      #   run: npm test

      - name: Pull translations (i18nexus)
        run: npm run pull-translations
        env:
          I18NEXUS_API_KEY1: ${{ secrets.I18NEXUS_API_KEY1 }} # gg:ignore
          I18NEXUS_API_KEY2: ${{ secrets.I18NEXUS_API_KEY2 }} # gg:ignore

      - name: Build Next.js app
        run: npm run build
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: 1
          DISABLE_WEBPACK_CACHE: true

      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          start: npm run dev
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
        env:
          NODE_ENV: test
          NEXT_PUBLIC_HCAPTCHA_TEST: true
